### ISSUE TITLE
Keyboard type showing alphabet 

### ISSUE THREAD

**Issue by snairsumith** [edwardfhsiao/react-codes-input#1]
when I set the type to the number but the keyboard showing alphabet . Check the screenshot 
![WhatsApp Image 2020-05-22 at 1 25 05 AM](https://user-images.githubusercontent.com/8740519/82600267-48301b00-9bcb-11ea-98ad-258195324981.jpeg)

**Comment by edwardfxiao** [comment]
Because the hidden input's type is the password for a better security reason, so while you focus the box, you are focusing on the real input.

The intention of the prop ```type``` here is for not allowing other types of value to enter, not to wakeup specific type of keyboard.

However, it is an improvement.

**Comment by edwardfxiao** [comment]
Hi @snairsumith , please check the version of ```1.2.1```
