### ISSUE TITLE
bug: with function buttons

### ISSUE THREAD

**Issue by bulhiCzar** [edwardfhsiao/react-codes-input#10]
https://user-images.githubusercontent.com/70818351/155530860-7e0cc882-ca59-4865-a657-d58fc60db430.mp4

**Comment by edwardfxiao** [comment]
I didn’t get that, can you explain a little?

**Comment by bulhiCzar** [comment]
type = alphanumeric
I press ALT, TAB, WIN, F7, F8 and so on
and it substitutes this value

**Comment by edwardfxiao** [comment]
I really can't reproduce this.

Does it only happen with ```type = alphanumeric```?

Can you reproduce it here? I mean does it happen when you are on this page too?
https://codesandbox.io/s/index-6hnbf

**Comment by bulhiCzar** [comment]
I can't repeat it in any of your projects, but in all of mine there is a bug
if type = number, then pressing F8 will put 8

**Comment by edwardfxiao** [comment]
"then pressing F8 will put 8"
You mean just press F8 or combine with the Fn key?

**Comment by bulhiCzar** [comment]
my keyboard has this, but I do it without pressing FN

**Comment by edwardfxiao** [comment]
@bulhiCzar And are you sure it is the ```v2.1.2```?

**Comment by bulhiCzar** [comment]
I used 2.0.9
sorry

there was such a bug

**Comment by edwardfxiao** [comment]
No problem, sometimes I update too many versions and I know its not good practice
