### ISSUE TITLE
feat: add switching by cells with arrows on the keyboard

### ISSUE THREAD

**Issue by bulhiCzar** [edwardfhsiao/react-codes-input#11]
key LEFT and RIGHT
the corresponding click moves the focus to the left or right

**Comment by edwardfxiao** [comment]
@bulhiCzar Heavy load work, can you test ```v2.1.3``` for this? Maybe a little bit buggy.

**Comment by bulhiCzar** [comment]
good its worked

**Comment by edwardfxiao** [comment]
@bulhiCzar Can you help me test ```v2.1.4```?  I enabled the ```tab``` ```Shift + Tab``` keys as the arrow keys as well
