### ISSUE TITLE
feat: redo the styling

### ISSUE THREAD

**Issue by bulhiCzar** [edwardfhsiao/react-codes-input#12]
I'll do it myself, on the weekend, or when I have time

**Comment by edwardfxiao** [comment]
```v2.1.5``` Removed class name hash

**Comment by edwardfxiao** [comment]
@bulhiCzar Close for now, you can reopen later. 

BTW, I found your avatar very interesting then I did a little research, turns out it is an hippop album cover and I like the album very much, although I don't speak nor read Russian!
