### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by alyona-mordas** [edwardfhsiao/react-codes-input#13]
Hi, 
I keep seeing this error on any page I include ReactCodesInput element
I have react ^18.2, react-dom ^18.2 and react-codes-input ^2.1.5 

I just return this in my component :     
`<ReactCodesInput
      initialFocus={false}
      codeLength={4}
      type="alphanumeric"
      hide={false}
      placeholder="#"
    />`
and it causes the error: 
<img width="861" alt="Screenshot 2022-07-01 at 14 27 38" src="https://user-images.githubusercontent.com/95859516/176894306-c4abc5ad-5f37-4d4a-9b2b-993553a5f515.png">

I am using SSR

**Comment by edwardfxiao** [comment]
@alyona-mordas Hi,

Thank you for your feedback, please check `v2.1.6` to see if it has any problems.

**Comment by alyona-mordas** [comment]
It is rendered now, though there is this warming message in the console 

<img width="644" alt="Screenshot 2022-07-01 at 14 57 17" src="https://user-images.githubusercontent.com/95859516/176899046-665bdb6a-acba-43f9-9d3b-941a2f3cc217.png">

**Comment by edwardfxiao** [comment]
weird, I'm using https://github.com/vercel/next.js/tree/canary/packages/create-next-app and don't see this error.

Maybe one way to avoid this issue is to check if it is SSR, if it is then don't include the component?

**Comment by edwardfxiao** [comment]
My index.js goes like this, and I don't see any error

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/11728228/176901745-4d41de36-ce1c-4945-aee4-3404d18260c4.png">
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/11728228/176902007-8a305592-32e3-4363-82cf-249500d5aab1.png">

**Comment by edwardfxiao** [comment]
@alyona-mordas Ok I know what is going on now, you did not pass `id`. Try giving it an `id`

**Comment by edwardfxiao** [comment]
Because if you don't pass it, I will generate a random `id` for its use, which won't match for a second time.

<img width="838" alt="image" src="https://user-images.githubusercontent.com/11728228/176906856-fefdfc08-5dd0-4696-92c6-b0ead2d25e44.png">

**Comment by alyona-mordas** [comment]
right, that fixed it, thanks a lot !
