### ISSUE TITLE
Can't input code on Android 

### ISSUE THREAD

**Issue by alyona-mordas** [edwardfhsiao/react-codes-input#15]
Hi again,
I just encountered one more issue with typing in code on Android, it simply doesn't seem t do anything (see the video attached)
Also tested it with [https://edwardfxiao.github.io/react-codes-input/](this) demo and had the same behaviour.
[](url)
I tried with v2.1.7 and v2.1.8.

Do you have any suggestion how to overcome this issue, please ?
Thank you

**Comment by edwardfxiao** [comment]
I will take a look tmr

**Comment by edwardfxiao** [comment]
Yes, it is a thing that Android handles differently(cannot get code from `keydown` event). Now I have to try it on its special `textInput` event.

Try `2.1.9`

**Comment by edwardfxiao** [comment]
@all-contributors please add @alyona-mordas for bug

**Comment by alyona-mordas** [comment]
It's fixed, thanks a lot for your effort !

**Comment by alyona-mordas** [comment]
Hello guys,

I think that issue still persist on Android in Firefox browser
Could you please have a look, when you have chance?
Thanks!

**Comment by edwardfxiao** [comment]
@alyona-mordas try `2.2.2`. I guess the original issue only occurred with chrome on android. So the changes were applied to other browsers too. Now I am only targeting on android chrome.

**Comment by alyona-mordas** [comment]
That worked. Thank you very much.
