### ISSUE TITLE
Shift key enabled?

### ISSUE THREAD

**Issue by darrylsepeda** [edwardfhsiao/react-codes-input#17]
I understand that the input field itself already auto uppercase (using props upper),
but how to enable shift key while user input the value?

current behavior shows nothing change when user hold shift while entering the value.
if it is not possible, is there any event listener such as key down or key up that I could override?

**Comment by edwardfxiao** [comment]
Can you provide a scenario / use case that you need to enable shift key for me to understand more of this request?

**Comment by darrylsepeda** [comment]
based on our initial user testing, we have found a number of users who behave this way. I do not want to block or confuse the user when entering the code with or without shift key. Is it possible to maintain the auto capitalisation and entry of the letters irrespective of whether the user is pressing the shift or not?

**Comment by edwardfxiao** [comment]
It is a valid request, I'm going to provide a `letterCase="auto"` option

**Comment by edwardfxiao** [comment]
@darrylsepeda Hi, can you try `v2.2.0` and make `letterCase="auto"`?

**Comment by darrylsepeda** [comment]
Great, it works, many thanks @edwardfxiao !
