### ISSUE TITLE
A client-side exception has occurred: Cannot read properties of null (reading 'removeEventListener')

### ISSUE THREAD

**Issue by alyona-mordas** [edwardfhsiao/react-codes-input#18]
Hello, 

I think we have encountered one more issue with Android + Chrome browser

When I type in the input, click submit and go to another page, I receive this error:
<img width="435" alt="Screenshot 2022-08-08 at 16 24 41" src="https://user-images.githubusercontent.com/95859516/183440912-a3394032-1280-4512-bab1-744322e9a84d.png">
<img width="1090" alt="Screenshot 2022-08-08 at 16 25 16" src="https://user-images.githubusercontent.com/95859516/183441060-178d4d11-3a54-40ef-af97-d813e22a9fc8.png">

looks like it is coming from this part of the code 
<img width="691" alt="Screenshot 2022-08-08 at 16 31 37" src="https://user-images.githubusercontent.com/95859516/183442528-f7f5c119-4b55-42f1-b5d5-df99a9fc4ea8.png">

I tried to provide the wrapperRef parameter , but that didn't help.

Any suggestions about that, please ?

I am using ^2.1.9 version

Thank you !

**Comment by edwardfxiao** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/11728228/183442580-b47cd5c2-00a6-4b83-9307-de75e9c5b08c.png">

`2.1.10` might fix it. But try the latest
