### ISSUE TITLE
Is there a way to enable copy & paste on react-codes-input?

### ISSUE THREAD

**Issue by darrylsepeda** [edwardfhsiao/react-codes-input#19]
I couldnt find any attribute to do copy & paste to this input field.
Is there a way for user to copy and paste the value to the input fields?
or if there is any onKeyUp/onKeyDown/onKeyPress, that might help as well I think.

**Comment by edwardfxiao** [comment]
Sorry, it is not easy to do for now.

Because ```onKeyDown``` function needs to avoid e.ctrlKey, e.altKey, e.shiftKey, e.metaKey from being pressed.

I suggest you create a paste button on the side by using
```js
  <div
    onClick={async () => {
      const text = await navigator.clipboard.readText();
    }}
  >
    paste
  </div>
```

But the downside is that you need a `https` environment to do that. If you have any better solution, a PR is very welcome.

**Comment by edwardfxiao** [comment]
Actually, I could try to enable `e.metaKey` and `e.ctrlKey` to make it work. But I don't have a Windows pc, and it might be going to be a little buggy.

**Comment by darrylsepeda** [comment]
yeah, I thought the same, I think it is possible by listening to event keydown, I'll try first now

**Comment by edwardfxiao** [comment]
![image](https://user-images.githubusercontent.com/11728228/192187966-1bed66fd-67b2-43d1-8dd8-f46f20671356.png)

And it has so much more to handle.

I guess I will just stay with the current solution(a  `paste` button on the side) until we find a much better one.

**Comment by darrylsepeda** [comment]
you're right.. the pointer/ selected box is buggy when user use paste function on non-complete code.
as long as user paste a complete code, everything works fine.

```
useEffect(
    () => {
      const eventName = 'keydown';
      const isSupported = window && window.addEventListener;
      if (!isSupported) return;
      const pasteCode = async (e: any) => {
        if ((e.ctrlKey || e.metaKey) && e.keyCode == 86) {
          // do something
       }
      }
      window.addEventListener(eventName, pasteCode);
      return () => {
        window.removeEventListener(eventName, pasteCode);
      };
    },
    [window]
  );
```

but so far I'm happy with this approach, thank you.
I appreciate your fast response!
