### ISSUE TITLE
add @types fro TS

### ISSUE THREAD

**Issue by bulhiCzar** [edwardfhsiao/react-codes-input#2]
the best thing is
that there is no girlfriend TS, I can't take to my project(

**Comment by edwardfxiao** [comment]
Hi @bulhiCzar , do I need to write it with typescript or just add some configuration?

**Comment by bulhiCzar** [comment]
you need to create a request for MR in the @type library
in the directory ./type

https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by edwardfxiao** [comment]
what is wrong with this method?
```js
{
  "compilerOptions": {
    "allowJs": true
  }
}
```
https://stackoverflow.com/questions/41219542/how-to-import-js-modules-into-typescript-file

**Comment by bulhiCzar** [comment]
people write to the TS to avoid problems with obscurity in the props of the component

for libraries , you need to generate .d.ts files that describe the entire typing
by setting allowJs you kill the point of writing on TS

**Comment by edwardfxiao** [comment]
Give me couple days, I will rewrite it with TS

**Comment by edwardfxiao** [comment]
@bulhiCzar Please try ```v2.0.5``` see if there is any problem.

**Comment by bulhiCzar** [comment]
I can't get import props from the library
![изображение](https://user-images.githubusercontent.com/70818351/155131248-b1c3e3f8-27a2-421c-bfe5-fd5c4f2c912b.png)

**Comment by edwardfxiao** [comment]
I’m really new to typescript, I’m not sure what the problem that is. All I can test is I import the library to a create-react-app typescript project and it seems to work fine.

Is it possible to make a pull request help me to do it better?

**Comment by bulhiCzar** [comment]
done. test this pls

**Comment by edwardfxiao** [comment]
I definitely will test it tomorrow, thank you
