### ISSUE TITLE
focus on Safari

### ISSUE THREAD

**Issue by alyona-mordas** [edwardfhsiao/react-codes-input#20]
Hi team,

I am struggling with one more issue.
I have multiple (two) ReactCodesInput components on the page and for some reason on Safari browser it focuses in the second one. I was trying to overwrite this behaviour specifying`  initialFocus={true} `and `{false}` for the first and second one respectively and also by setting focus in the code on the created reference 
`pinWrapperRef1.current.firstChild.focus();` 
None of these helped. 

I attach the code snippet with the component usage here: 

`
<ReactCodesInput
              initialFocus={true}
              wrapperRef={$pinWrapperRef1}
              id="tv-login-code1"
              codeLength={4}
              type="number"
              hide={false}
              placeholder="####"
              value={pin1}
              onChange={(res) => {
                setPin1(res);
              }}
              classNameWrapper={styles.codeInputWrapper}
              classNameEnteredValue={styles.codeEnteredValue}
              customStyleComponent={{
                marginRight: "2%",
                width: "48%",
                display: "inline-block",
              }}
            />

            <ReactCodesInput
              initialFocus={false}
              wrapperRef={$pinWrapperRef2}
              id="tv-login-code2"
              codeLength={4}
              type="number"
              hide={false}
              placeholder="####"
              value={pin2}
              onChange={(res) => {
                setPin2(res);
              }}
              classNameWrapper={styles.codeInputWrapper}
              classNameEnteredValue={styles.codeEnteredValue}
              customStyleComponent={{
                marginLeft: "2%",
                width: "48%",
                display: "inline-block",
              }}
            />`

Could you take a look, please ? 

<img width="425" alt="Screenshot 2022-10-04 at 15 55 22" src="https://user-images.githubusercontent.com/95859516/193838448-8ebfd93b-5d4f-4919-b05c-55eb373059bc.png">

**Comment by edwardfxiao** [comment]
@alyona-mordas Hi, sorry for the delay. Try `v2.2.3`.

I have commented out the line `$inputRef.current.setSelectionRange(curItemIndex, curItemIndex);`, which cause the problem.

And honestly I cannot remember why I wrote this line, maybe it was for IE9, or maybe it was for something else, I am not sure. So it may cause other issues. Please help me test it, thank you.

**Comment by alyona-mordas** [comment]
it seems like that fixed it, thank you !
so far we didn't spot any other issues, if we notice anything later, I will let you know

**Comment by alyona-mordas** [comment]
Hello team, 
I just noticed another small issue with focus on the component, so it focuses on the correct component, but always on the first cell. It's not a breaking issue, but not quite optimal for the UI experience. I attach the video displaying the behaviour. Would appreciate your help on this !

https://user-images.githubusercontent.com/95859516/235937632-5455a8bc-c763-46d8-8043-89a5cbd23f59.mov

**Comment by edwardfxiao** [comment]
1, In your video, it keeps focusing on the last cell. Shouldn't it be focusing on the first one instead?
2, I intentionally made it focus on the first value that is undefined. What would you prefer it to do? Should it focus on the cell wherever the user clicks?

**Comment by alyona-mordas** [comment]
Yes, I meant it focuses on the last cell, sorry. It would be perfect if by default it focuses on the first cell, and if user clicks on a different cell the focus would be there

**Comment by edwardfxiao** [comment]
Sorry, in that case, there would be too much to handle. I am afraid it is out of the scope.

**Comment by alyona-mordas** [comment]
I see, would it be too much effort to make it focus just on the first on instead of the last ?

**Comment by edwardfxiao** [comment]
I don't know why does it on the last cell in your video, cuz in my demo, it focuses on the first

**Comment by alyona-mordas** [comment]
Ok, thank you, I will try to find solution on my side
