### ISSUE TITLE
add the required option

### ISSUE THREAD

**Issue by bulhiCzar** [edwardfhsiao/react-codes-input#6]
add this code to the component itself, which will intercept onSubmit

![изображение](https://user-images.githubusercontent.com/70818351/155167265-f381eff3-27b3-4026-b476-6fb042a92c2b.png)

**Comment by edwardfxiao** [comment]
I don't see the reason why should I put this into the component itself, and I don't know where should it go also.
Can you explain more?

**Comment by bulhiCzar** [comment]
you have a fake input, set the required and min-length rule
to it and pass value, then at least submit will not pass because of the input conditions

if it's more complicated, then you need your own layout form,
where you accept onSubmit, do a check and continue to perform onSubmit if everything is fine

**Comment by edwardfxiao** [comment]
Try ```v2.1.2```

one thing I can't work around is this in the ```sandbox example```
https://codesandbox.io/s/index-6hnbf?file=/package.json on Chrome.

![image](https://user-images.githubusercontent.com/11728228/155474641-ea551288-735c-42a5-8f76-ba4a2a7d7496.png)

While in the real project seems working fine though.

**Comment by bulhiCzar** [comment]
yes, is working
