### ISSUE TITLE
bug with type = number

### ISSUE THREAD

**Issue by bulhiCzar** [edwardfhsiao/react-codes-input#7]
when you do not enter a number, the value disappears, but is written to the store, and if you erase the value, then when the numbers remain, then everything works correctly

start typing numbers first, then letters, an error will appear

**Comment by edwardfxiao** [comment]
Sorry, I don't quite follow you here.
Would you plz post a .gif to demonstrate the bug?

**Comment by bulhiCzar** [comment]
https://user-images.githubusercontent.com/70818351/155288280-463b4977-d59a-4123-8b3e-04c34cd6f0a1.mp4

**Comment by edwardfxiao** [comment]
@bulhiCzar Ok, it's firefox only I see now, and safari

**Comment by edwardfxiao** [comment]
Can you test this for me? ```v2.0.9```.
I will look at the other issue tomorrow.

**Comment by bulhiCzar** [comment]
fixed
